### ISSUE TITLE
No administrator user

### ISSUE THREAD

**Issue by disaster37** [gocd/gocd-ldap-authentication-plugin#36]
Hi,

There are a way to not create LDAP user as GoCD administrator ?
In default setting, all LDAP user are administrator after the first login in GoCD 17.10.0.

Best Regards,
disaster

**Comment by arvindsv** [comment]
Can you check what happens if you make one of the users [a "Go System Administrator"](https://docs.gocd.org/current/configuration/managing_users.html#managing-go-system-administrator-privilege)?

**Comment by phreddrick** [comment]
I'm running into this too.. Basically, I'm in a large corporate infrastructure, and I to use LDAP to make my life easier, but I don't want it to make every user that logs in with their LDAP credentials to be a Go System Administrator by default, is there anyway to configure that to have some other default?

**Comment by disaster37** [comment]
Hi,

can you try to put your LDAP account user as "Go System Administrator". After that, the new LDAP user come without any right in my case.

**Comment by arvindsv** [comment]
Yes. Closing this. You should be able to make any one (at least one) user "Go System Administrator" and from then on, everyone else will not become super admin by default. I can reopen this, if it's not the case.
