### ISSUE TITLE
Can I configure it to use multiple servers (as fallback)?

### ISSUE THREAD

**Issue by MPV** [gocd/gocd-ldap-authentication-plugin#37]
In the case my first server is down, but my second one is up — does this support configuring to have a fallback LDAP server? 

Would I then have multiple `Url` properties? 
Or multiple `<authConfig>`s?

**Comment by bdpiparva** [comment]
@MPV --- Yes, you can have multiple`<authConfig/>`s to authenticate user. It try to authenticate user using first `<authConfig/>` if it fails to authenticate user then it uses the next one.
